### ISSUE TITLE
when i use several node types,how to write feature.txt

### ISSUE THREAD

**Issue by neuronblack** [THUDM/GATNE#10]
..

**Comment by cenyk1230** [comment]
A good question! You can merge the node features of different node types. For example, if the node features of two node types are (x1, x2, ..., xn) and (y1, y2, ..., ym), the merged node features are then (x1, x2, ..., xn, 0, ... 0) and (0, ..., 0, y1, y2, ..., ym), respectively.

**Comment by neuronblack** [comment]
3q
