### ISSUE TITLE
cold start nodes' embedding

### ISSUE THREAD

**Issue by mohit-udaan** [THUDM/GATNE#11]
When we have nodes which do not have edges (because of cold start) we currently do not get embeddings for them. Can we add the feature for getting the node embeddings even when they do not have edges which is the novel output from GATNE-I.

**Comment by cenyk1230** [comment]
Sorry. I will add this feature soon.

**Comment by mohit-udaan** [comment]
I couldn't find the code changes to include the cold-start nodes. I didn't see any code pushes recently. Can you please point me to the same as you have closed this issue. Thanks a ton!

**Comment by colby-ham** [comment]
I'm still trying to figure out the same thing as @mohit-udaan.
