### ISSUE TITLE
Validation set not used for parameter tuning

### ISSUE THREAD

**Issue by AdithyaSelvaganapathy** [THUDM/GATNE#13]
Novel idea and great work for generation node embedding for AMHEN graphs.

My doubt is according to the paper the validation set has to be used for parameter tuning, however in the code implementation the validation set has been used just for calculating performance metrics. Could you please clarify?

**Comment by cenyk1230** [comment]
The validation set is mainly for early stopping. Parameter tuning may be a little misleading. Thank you for your comments!
