### ISSUE TITLE
Can you assign a release to this project please?

### ISSUE THREAD

**Issue by abmitra84** [THUDM/GATNE#16]
Please put a release number in `Release`.. Thanks and Appreciate

**Comment by cenyk1230** [comment]
May I ask why you need a release number?

**Comment by abmitra84** [comment]
Hi,

I have some bureaucratic requirements for this in order for me to access it – tremendously appreciated and sorry for the inconvenience

Thanks

**Comment by cenyk1230** [comment]
I have released a v1.0 version of GATNE.
