### ISSUE TITLE
得到的嵌入为0

### ISSUE THREAD

**Issue by xiangyuwei** [THUDM/GATNE#17]
在自己的数据集上（有特征）运行代码，会有部分节点最终得到的嵌入为0，请问这是什么原因呢，有什么好的建议怎么去做修改和排查呢

**Comment by cenyk1230** [comment]
目前的代码只能得到训练集中出现过的节点的embedding，所以你说的应该是那些未在训练集中出现过的节点吧？

**Comment by xiangyuwei** [comment]
不是，节点在训练集中出现过，evaluate的时候报错， ValueError: Input contains NaN, infinity or a value too large for dtype('float32'). 然后发现有的节点嵌入为0

**Comment by cenyk1230** [comment]
如果你还是找不出原因的话，可以考虑把数据集发给我，我帮你看下。

**Comment by xiangyuwei** [comment]
请问数据集构造除了节点必须在训练集中出现还有什么要求吗

**Comment by cenyk1230** [comment]
要不你试下把edge type忽略掉之后用DeepWalk跑个结果看看？

**Comment by RocccYan** [comment]
> 不是，节点在训练集中出现过，evaluate的时候报错， ValueError: Input contains NaN, infinity or a value too large for dtype('float32'). 然后发现有的节点嵌入为0

我也遇到了一样的问题，请问后续有什么解决思路不？
