### ISSUE TITLE
大规模图如何处理

### ISSUE THREAD

**Issue by Andy1314Chen** [THUDM/GATNE#18]
想请问一下，对于较大规模异构图，是如何处理的？（主要是前期random walk）现在采样了约80万节点，单机跑不动

**Comment by cenyk1230** [comment]
可以考虑减少num-walks和walk-length，然后把random walk的结果或者train pairs的结果预处理好存在本机？

**Comment by Andy1314Chen** [comment]
谢谢回复，我再尝试一下
