### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by xiangyuwei** [THUDM/GATNE#21]
请问twitter 和youtubu 有关于特征部分的数据集吗？如果有是否可以提供下载呢？

**Comment by cenyk1230** [comment]
可以自己在这两个数据集的训练数据上跑个DeepWalk作为特征。DeepWalk的代码可以参见https://github.com/phanein/deepwalk/。

**Comment by Crice22** [comment]
请问您有像画的图那样的数据集吗，例如，假如有三种类型节点，两两之间可能存在相同的关系类型：A-B = A-C

**Comment by xiangyuwei** [comment]
谢谢，再请教一个问题，从原始数据集中采样数据进行实验，采样方式是什么，采样了多少数据，是随机采样吗？

**Comment by cenyk1230** [comment]
随机选取了一些seed节点进行BFS/DFS得到采样的节点集，然后保留这些节点之间的连边。
