### ISSUE TITLE
questions about the amazon dataset.

### ISSUE THREAD

**Issue by blldd** [THUDM/GATNE#22]
Could you please explain how you preprocess the amazon dataset, like what type you choose, how to sample, and how to generate feature data, etc ..., thank you for your time:)

**Comment by cenyk1230** [comment]
We use these two types ("also_bought" and "also_viewed") in the Amazon dataset. And we use the breadth-first search (BFS) method to sample a connected subgraph. The feature data is generated by one-hot encoders on categorical attributes of Amazon items.
