### ISSUE TITLE
关于表格中网络类型的分类

### ISSUE THREAD

**Issue by Crice22** [THUDM/GATNE#23]
请问一下，metapath2vec 和 PTE 放到 HEN （多类型节点，单类型边）是如何考虑的呢，这两个困扰我好久了，感谢

**Comment by cenyk1230** [comment]
感谢你的关注，这确实是个很好的问题。在我们的定义下，multiplex主要考虑的是两个节点之间可能存在多条(不同类型的)边。而这两种方法处理的网络中，两个节点之间至多只有一条边，所以我们将其归为HEN。

**Comment by Crice22** [comment]
原来是这样，一直想成是整个网络的边类型，感谢 ：)
