### ISSUE TITLE
程序运行错误

### ISSUE THREAD

**Issue by rrsun** [THUDM/GATNE#24]
Traceback (most recent call last):
  File "src/main.py", line 415, in <module>
    average_auc, average_f1, average_pr = train_model(training_data_by_type, feature_dic, log_name + '_' + time.strftime('%Y-%m-%d %H-%M-%S',time.localtime(time.time())))
  File "src/main.py", line 363, in train_model
    tmp_auc, tmp_f1, tmp_pr = evaluate(final_model[edge_types[i]], valid_true_data_by_edge[edge_types[i]], valid_false_data_by_edge[edge_types[i]])
KeyError: '3'

你好，请问当我用自己的数据运行程序的时候，出现了这样的错误，是我的数据有问题吗？

**Comment by Macvh** [comment]
你好，我也是遇到了这个问题，请问你是怎么解决的

**Comment by luolo-cry** [comment]
> 你好，我也是遇到了这个问题，请问你是怎么解决的

你好，今天我也遇到了这个问题，请问你知道如何解决吗？感谢！

**Comment by luolo-cry** [comment]
> Traceback (most recent call last): File "src/main.py", line 415, in average_auc, average_f1, average_pr = train_model(training_data_by_type, feature_dic, log_name + '_' + time.strftime('%Y-%m-%d %H-%M-%S',time.localtime(time.time()))) File "src/main.py", line 363, in train_model tmp_auc, tmp_f1, tmp_pr = evaluate(final_model[edge_types[i]], valid_true_data_by_edge[edge_types[i]], valid_false_data_by_edge[edge_types[i]]) KeyError: '3'
> 
> 你好，请问当我用自己的数据运行程序的时候，出现了这样的错误，是我的数据有问题吗？
你好，今天我也遇到了这个问题，请问你知道如何解决吗？感谢！

**Comment by Wandaboma** [comment]
Hello, I've encountered the same problem, can anyone tell me how should I change my dataset?
