### ISSUE TITLE
增加节点类型

### ISSUE THREAD

**Issue by rrsun** [THUDM/GATNE#25]
你好，请问增加node_type.txt后除了修改schma，还需要调整代码吗？还有可以用字符串表示节点吗？

**Comment by cenyk1230** [comment]
感谢你的关注！应该是不需要的。可以用字符串表示节点。

**Comment by rrsun** [comment]
谢谢你的回复，今天我增加了node_type.txt后发现生成的vocab好像没有全部覆盖walk，导致在生成pairs时候vocab[work[i]].index在vocab里面查找不到键，这是因为还要加feature文件才行吗？还是别的原因呢？

**Comment by cenyk1230** [comment]
照理来说应该不会出现这种情况呀。这个问题你现在解决了吗？

**Comment by rrsun** [comment]
> 照理来说应该不会出现这种情况呀。这个问题你现在解决了吗？

你好，这个问题已经解决了，请问你们是怎么做基线模型对比的吖？训练的节点是只包括每一类的节点，还是用所有类的节点训练呢？

**Comment by cenyk1230** [comment]
对每种类型的边分别预测，然后求平均。具体可以参见论文5.3节的开头一段，或者直接看代码。
