### ISSUE TITLE
node type 

### ISSUE THREAD

**Issue by ZanyFun9** [THUDM/GATNE#26]
没有看弄您说的node type文件格式‘--schema node_type_1-node_type_2-...-node_type_k-node_type_1’
这个是什么意思

**Comment by cenyk1230** [comment]
假设有两种类型的节点，比如U和I（分别表示User和Item）。那么可以指定meta-path schema为U-I-U或者I-U-I。在random walk的过程中会根据这个schema来确定下一个节点的node_type。
