### ISSUE TITLE
Non-edge

### ISSUE THREAD

**Issue by CigaLi** [THUDM/GATNE#27]
您好，请问在数据文件test.txt和valid.txt中”**label**”为0表示的“non-edge”是什么意思呢？是指数据中不存在这条边吗？我在准备自己的数据时应该怎样为”**label**”赋值呢？谢谢

**Comment by cenyk1230** [comment]
您好！
label=0的non-edge指的是原本graph中不存在的边。你可以随机选取一些不存在的边作为non-edge (label=0)。原本的graph中存在的被划分到valid和test集中的边的label设为1。
