### ISSUE TITLE
运行amazon例子的时候报错了

### ISSUE THREAD

**Issue by HollyHANG** [THUDM/GATNE#28]
运行时出了这个错误
File "src/main.py", line 363, in train_model
    tmp_auc, tmp_f1, tmp_pr = evaluate(final_model[edge_types[i]], valid_true_data_by_edge[edge_types[i]], valid_false_data_by_edge[edge_types[i]])
KeyError: 'Base'
sample运行的时候没出问题的时候edge_type变量是['1', '2', 'Base']
Amazon print出来的edge_type变量是['2', 'Base', '1']
请问这个问题该怎么解决啊……

**Comment by cenyk1230** [comment]
Hi @HollyHANG,
多谢指出这个问题！应该是不同python版本导致的问题。我改了一下代码，保证了'Base'始终出现在edge_types的最后。
