### ISSUE TITLE
边权重的问题

### ISSUE THREAD

**Issue by xingzeliang** [THUDM/GATNE#3]
请问每行是否需要去重复，如果去重复那么边的权重怎么表示

**Comment by cenyk1230** [comment]
代码暂时没有考虑边的权重。边的权重在你的问题里重要吗？或者你可以自己先试下能不能在random walk的时候考虑进边的权重？或者暂时先不考虑权重？

**Comment by xingzeliang** [comment]
因为点击、购买、加车的行为权重是不同的，我先不加权重看下效果

**Comment by xingzeliang** [comment]
请问分布式版本是否开源，单机运行太慢了

**Comment by cenyk1230** [comment]
你要跑多大规模的图？你可以先sample一个小的数据集试一下效果

**Comment by xingzeliang** [comment]
大概有200w node 和 5000w edge
