### ISSUE TITLE
请问支持节点连边权重吗？

### ISSUE THREAD

**Issue by xuetf** [THUDM/GATNE#33]
您好：
    我看了readme.md，发现里头准备数据一节中没有涉及到边的权重，请问是不支持连边权重的设置吗? 谢谢

**Comment by Refrainlhy** [comment]
issue 9

**Comment by xuetf** [comment]
> issue 9

请问如果要实现根据权重采样的话，修改walk.py即可是吗？

**Comment by cenyk1230** [comment]
Hi @xuetf,

我看了一下，在utils.py中读入数据的时候也需要修改。

**Comment by nlpxjg** [comment]
> 您好：
> 我看了readme.md，发现里头准备数据一节中没有涉及到边的权重，请问是不支持连边权重的设置吗? 谢谢

您好，请问你对边加权重实现了吗！
谢谢您！
