### ISSUE TITLE
Embedding for cold start nodes

### ISSUE THREAD

**Issue by NDS-98** [THUDM/GATNE#35]
The paper mentions a great way to tackle the **cold start problem** by considering the node attributes while generating the embeddings in case of GATNE-I. So ideally, a node that is not connected to any other node, should also have embedding based on it's features, so that for a new user, we can recommend on the basis of his attributes considering no previous connections. 
Can you please point out at the part of code that deals with this problem?
Thank you in advance!

**Comment by cenyk1230** [comment]
Hi @NDS-98,

Sorry. GATNE-I has the ability to tackle the cold start problem. But the current version of the code is mainly for experiments of the paper and doesn't support this feature. We may support this in the future.

**Comment by NDS-98** [comment]
Thanks for your reply @cenyk1230 !

I was actually working on extracting the embeddings of the cold start nodes as well. For that we need to introduce isolated nodes in our input graph. I tried two methods:

Firstly, I tried making isolated nodes and included a self-edge for each of them in order to generate the walks and took unique walks into consideration (because the walks starting from such nodes will contain only that specific node owing to the self-loop). But seems that the idea didn't help because the initial conditions say that the input graph must be connected.

Secondly, I tried connecting such isolated nodes with the input graph with a different kind of edge in order to maintain the connectedness, but then we would start getting wrong recommendations because these edges would be counted as normal in the base walk generation and hence we won't actually be creating isolated nodes.

Can you please suggest where I'm going wrong or some other way for the generation of cold start node embeddings?
I would be happy to create a pull request for everyone to use as well.

**Comment by cenyk1230** [comment]
Hi @NDS-98,

Extracting the embeddings for cold-start nodes mainly relies on the node attributes. From equation (13) in the paper, we can compute the embedding of a cold-start node by the node attribute of itself and its neighbors if possible.
