### ISSUE TITLE
关于数据集构建

### ISSUE THREAD

**Issue by Woooosz** [THUDM/GATNE#36]
以Amazon数据集为例，请问您是如何对数据进行预处理的呢？
（从Raw Data 转化为 node_type node_A node_B格式）
我的一个猜想：已知用户评分序列（按照时间先后）为A->B->C->D->E
生成node_type node_A node_B对为
1 A B
1 B C
1 C D
1 D E
请问您是这样处理的吗，请多多指教，谢谢！

**Comment by DoufuX** [comment]
同问数据预处理方法，以及想知道是否可提供数据预处理的代码？

**Comment by cenyk1230** [comment]
Hi @Woooosz,

Amazon数据集我们只用了item-item之间的多种类型的关系，没有考虑user。

**Comment by cenyk1230** [comment]
Hi @DoufuX,

Issue #22 可能对你有些帮助。

**Comment by Woooosz** [comment]
感谢回复 @cenyk1230 ！

我想了解一下您在Alibaba数据集上，数据预处理也是和Amazon一样的处理方式吗？如果不是的话，能否简单谈一谈在Alibaba数据集上数据预处理相关的技巧呢，感谢！

(我比较关心应用到具体的业务中落地方式

**Comment by cenyk1230** [comment]
Hi @Woooosz,

在Alibaba数据集上，我们把user, item都看成图中的节点，把user-item之间的多种交互行为当作图中的边。在这个图上学习节点表示然后根据学到的user/item embedding来推荐。

**Comment by Woooosz** [comment]
非常感谢！
