### ISSUE TITLE
What's the meaning of att_head?

### ISSUE THREAD

**Issue by siriussilen** [THUDM/GATNE#37]
What's the meaning of variable 'att_head'(default 1), I don't find any information on it?
Plz, tell me, Thanks

**Comment by cenyk1230** [comment]
Hi @siriussilen,

The variable `att_head` means the number of attention heads. You can see the original paper[1] of the attention mechanism about attention heads. In our work, we only use a single attention head, i.e., `att_head=1`. You can also change the value of `att_head` to enable the multi-head attention mechanism. 

[1] Vaswani, Ashish, et al. "Attention is all you need." Advances in neural information processing systems. 2017.
