### ISSUE TITLE
node embedding 和 k值问题

### ISSUE THREAD

**Issue by destinyJLU** [THUDM/GATNE#38]

**Comment by destinyJLU** [comment]
两个问题请教一下：
1. 最终的 node_emb是base_emb + edge-specific-node_emb ， final_model里面是不是只有 edge-specific-node_emb ？
2. 论文4.1中的K在代码里取值是1吗

**Comment by cenyk1230** [comment]
Hi @destinyJLU,

1) final_model里已经是两者之和了。
2) 是的。
