### ISSUE TITLE
How to get the embedding vector for each node?

### ISSUE THREAD

**Issue by nyy477** [THUDM/GATNE#39]
hi, very lucky to study your work! I found that the task in your code is to predict link relations between nodes, but I want to get the embedding result of each node. How can I get that? 
Thank you.

**Comment by cenyk1230** [comment]
Hi @nyy477,

You can see Issue #14.

**Comment by nyy477** [comment]
> Hi @nyy477,
> 
> You can see Issue #14.

Thanks!
