### ISSUE TITLE
新的nodes

### ISSUE THREAD

**Issue by Yuminzhou** [THUDM/GATNE#4]
您好，请问这个模型是否要求train set里需要包括所有可能出现的nodes？换句话说，valid set和test set里不可以出现新的nodes？谢谢。

**Comment by cenyk1230** [comment]
为了公平地和其他baseline进行比较，所以构建valid/test set时只用到了train set中出现过的nodes。GATNE-I模型理论上是可以得到新nodes的embs的，不过目前的代码还不支持这个功能。过段时间我会考虑加上这个功能的。

**Comment by Yuminzhou** [comment]
十分感谢您的回答，也期待您新的功能。
我还有个小问题，关于feature.txt:假如我的node是一个国家，有些feature是categorical的，比如“经济发展程度”（有分类发展中国家/发达国家）这样的情况，请问您的建议是如何处理呢？是one hot encoding吗？
谢谢。

**Comment by cenyk1230** [comment]
嗯嗯 一般用one hot encoding

**Comment by Yuminzhou** [comment]
好的，十分感谢
