### ISSUE TITLE
About comparative experiments

### ISSUE THREAD

**Issue by lalw** [THUDM/GATNE#43]
Hello, 
I want to do comparative experiments on my own dataset, but I didn't find the official python code of metapath2vec, so I'm sorry to ask, what is the metapath2vec code you are using for comparison experiments, can you share it?
Thank you very much!

**Comment by cenyk1230** [comment]
Hi @lalw,

Sorry for the late reply. We use an internal version of metapath2vec in Alibaba Group. Maybe you can use an unofficial code of metapath2vec or implement it on your own. The most important part of metapath2vec is the heterogeneous random walk, which can be easily implemented.

**Comment by lalw** [comment]
Thanks  for your answer！
I still have a problem, for example, performing random walks on the two metapaths of "Academy-Discipline-Project-Discipline-Academy" and "Academy-Project-Academy" to get the embeddings of Academy.
In addition to the Academy's embedding, it is also necessary to obtain the Discipline's embedding.
The metapath with Discipline as the starting point should be "Discipline-Project-Discipline". Then, based on the random walk of the metapath starting from the Academy, is the calculated Discipline's embedding correctly?
If not, can metapaths with different starting points be executed simultaneously in one model? Or should the model be executed multiple times for metapaths with different starting points?
Looking forward to your answer, thank you very much！

**Comment by cenyk1230** [comment]
The skip-gram method will train the embeddings of all the nodes in the random walks, rather than the embeddings of starting nodes in the metapaths. The Discipline's embeddings trained from random walks of scheme 1 can be directly used for downstream tasks.

**Comment by lalw** [comment]
Sorry, path 1 is wrong. It should be [1] "Academy-Project-Discipline-Project-Academy"
My concern is that this meta-path is not specifically set for Discipline. Can it fully capture semantic and structural information?
If there is another type of Node Researcher, which cannot be combined in the 1 or 2 path, can I set the path to [1]"Academy-Project-Discipline-Project-Academy" and [2] "Discipline-Project-Discipline" and [3]"Researcher-Project-Discipline-Project-Researcher" in one run to get all the embedding for all kinds of nodes?
I am a beginner,  have many questions, thank you for your patience!
