### ISSUE TITLE
About attributes

### ISSUE THREAD

**Issue by yathe** [THUDM/GATNE#44]
hi , I have some questions about equation (13).
How the attributes of nodes in GATNE-I are applied to calculate bi and ui,r(0)? 
How are hz and gz,r defined?
thank you !

**Comment by cenyk1230** [comment]
Hi @yathe,

The functions h_z and g_{z,r} can be parameterized as a trainable matrix. You can see the code for more details.

**Comment by yathe** [comment]
thanks!
