### ISSUE TITLE
Question on vertex embedding

### ISSUE THREAD

**Issue by snash4** [THUDM/GATNE#46]
Hi, 
I find the paper very interesting and to read through. 
However, I have a question regarding the final learned embedding.
In Algorithm 1, line 6, the model learns an embedding of a vertex specific to the relation, which is also evident through eq. 6 and 13. This means that a vertex has different embedding for each view. 
I could not find or understand in experimental section which embedding are you using for link prediction, OR are you combining these different embedding, if yes, then how?

Thanks.

**Comment by cenyk1230** [comment]
Hi, 

Thank you for your attention. For the link prediction task of each view, we use the corresponding node embedding of that view. The final experimental results are averaged among the selected views.
