### ISSUE TITLE
weighted graph

### ISSUE THREAD

**Issue by simonHorvat** [THUDM/GATNE#49]
Is it possible to execute your method for weighted graph?
Is there a theoretical problem why weighted heterogeneous network can't be vectorize? 
I found some nice looking implementation of node2vec and matapath2vec, but there is no possible to set weights for edge in case of matapath2vec.
Thank you for answer !

**Comment by cenyk1230** [comment]
Yes, it is possible for our model to run on weighted graphs. For our work, the procedure of random walk needs to be modified when considering weighted edges.

**Comment by CC-0918** [comment]
@cenyk1230 I have the same question as raised by @simonHorvat. 

My application scenario is that, for example, user A may 'read(consume)' content in a certain topic for 100 times, while 'write(contribute)' content in the topic for merely one time. In this case, when training the embeddings of user A under the reading and writing activities respectively, I would like to incorporate the frequency of these activities. Based on your last reply, it looks like it is possible to implement this idea by modifying the random walk procedure a bit.

But I still don't have a clear idea about where to start. Any suggestions, cues, or recommended literature? Thank you in advance!
