### ISSUE TITLE
What's the specific meaning of the four datasets

### ISSUE THREAD

**Issue by shiozakixlg** [THUDM/GATNE#50]
Hello,

I want to use your code and your datasets as a baseline method.

But the four datasets in the project just have the value of attributes, and don't have the specific meaning of them, thus I can't have a better understand of the datasets.

So could you please provide me the specific meaning of the attributes in the four datasets? Thank you.

**Comment by cenyk1230** [comment]
Hi,

Thank you for your attention to our work. Actually, the meaning of the attribute doesn't matter in our work. You can check the meaning for the Amazon dataset from the original page `http://jmcauley.ucsd.edu/data/amazon/`. YouTube and Twitter datasets have no attributes.
