### ISSUE TITLE
Apply GATNE-T to node classification task

### ISSUE THREAD

**Issue by CC-0918** [THUDM/GATNE#54]
Hi! Yukuo,

I'm excited to find your work. It's quite inspiring and related to a project that I'm recently working on. As I'm new to graph embedding, I have a few basic questions in terms of application.

I wonder whether GATNE can be applied to node classification. Because the experiments in your paper focus on link prediction, I'm curious whether it is feasible to apply the method to node classification problem? And how about the performance?

In the paper, it seems that you derive the node embeddings (in an unsupervised way) and then pass the embeddings to a downstream link prediction task (Am I right?). My question is, may I directly train the model for a specific supervised task (say, a node classification task)?

Best,
Ziwei

**Comment by cenyk1230** [comment]
Hi @CC-0918,

Thank you for your attention. GATNE is designed and tested only for multiplex link prediction. I'm not sure whether GATNE will get a good performance on node classification. You can try to apply GATNE to an unsupervised or supervised node classification task. But I recommend that you use some heterogenous GNNs designed for node classification, such as Graph Transformer Networks, Heterogeneous Graph Attention Network, Heterogeneous Graph Transformer. Some of them can be found at https://github.com/THUDM/cogdl.

**Comment by CC-0918** [comment]
@cenyk1230 

Thanks for your reply! I've also read these papers you recommended such as HAN. But I'm not quite sure whether they could handle multiple types of nodes and edges simultaneously.  May I seek for your opinion? Thanks!

**Comment by cenyk1230** [comment]
Hi @CC-0918,

Some of these papers transform the original heterogeneous networks into multi-view meta-path graphs and then use GNN for node classification. Maybe you can similarly transform your specific graph into multi-view meta-path graphs and use their models.

**Comment by CC-0918** [comment]
@cenyk1230 

Thanks! I would like to follow this idea and have a try. 

I also have an additional question that if my goal is just to get embeddings in order to do some descriptive analysis (let's ignore the node classification task now), would GATNE a suitable model? To be more specific: 

My application context involves both heterogeneous nodes as well as heterogeneous edges. For example, on Zhihu, a user could 'read' content under a certain topic, and he can also 'contribute (write answer)' to that topic. As a result, there are two different types of nodes (user and question), and user and question can be linked via two different edges ('read' and 'write'). My goal is to get embeddings of a user under the 'read' activity (which reflects the user's interest) and 'write' activity (which reflects the user's expertise level), respectively. (The derived embeddings should be in the same latent space so that they are comparable.)

If I simply want to get embeddings for each user under different edges (activities), would GATNE be a suitable method? Any suggestion? Thank you in advance!

**Comment by cenyk1230** [comment]
Hi @CC-0918,

It seems that this is a suitable scenario for GATNE. You can have a try but I'm not sure that GATNE works well for descriptive analysis.
