### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by Aliang-CN** [THUDM/GATNE#55]
您好！
       非常感谢你的开源工作。我有个问题想咨询一下你，这个数据集上面的1、2对应是论文上面图一的click、add-to-preference、add-to-cart、conversion吗，
1 104988 459811
1 478024 469070
1 153026 469507
1 199773 268852
1 407720 462844

**Comment by cenyk1230** [comment]
Hi @linxingliang,

For the amazon dataset, the meanings of different views are _also_bought_ and _also_viewed_. You can refer to the original website for more details: http://jmcauley.ucsd.edu/data/amazon/.
