### ISSUE TITLE
How to deal with node features of different dimensions

### ISSUE THREAD

**Issue by tearsroad** [THUDM/GATNE#56]
Hi, thanks for you excellent research.
I want to ask about the feature processing. After reading your paper, it is mentioned that the Alibaba dataset has 2 node types, which should be user and product types.
Are their two types of feature dimensions the same? If they are different, how do I deal with feature input? eg: user 50d, item 300d

**Comment by tearsroad** [comment]
already know

**Comment by viviqi** [comment]
hello, I have the same question now and I don't know how to solve it appropriately, it seems that you have come up with a solution, could you please share your ideas with me? thanks a lot!
