### ISSUE TITLE
关于大数据集训练问题

### ISSUE THREAD

**Issue by tearsroad** [THUDM/GATNE#57]
论文中Alibaba的数据， notes41,991,048  edges571,892,183。这么大的数据集需要对模型做什么样的优化，现在模型oom了。

**Comment by cenyk1230** [comment]
Hi @tearsroad,

Thank you for your attention. For the Alibaba dataset, we use a distributed version of GATNE based on Alibaba's internal platform. But this public version of GATNE can't handle the large-scale graph. Maybe you can try a smaller graph for your experiments.
