### ISSUE TITLE
关于多重边异构图的节点分类应用问题

### ISSUE THREAD

**Issue by shenRicky** [THUDM/GATNE#58]
你好，非常感谢分享如此棒的一篇文章。看到你的文章中对于多重边的异构图的链接预测问题有一个非常好的解决。
       我现在想要解决的是多重边的异构网络的节点分类问题，请问可以使用您的这个模型吗？我想要解决的场景是节点是二分类，除了标签外无特征的；两个节点间可能有多重边，每条边有多个特征。我看到您在给另一个节点分类问题中留言了一个异构网络节点分类的地址https://github.com/THUDM/cogdl ，我查阅了一下，其中的论文主要解决的都是异构网络问题，例如两个节点间拥有多种类型的边，但是节点间仅有一条边。对于两个节点间的多重边情况并没有提到如何解决，所以想听听您的看法？谢谢

**Comment by cenyk1230** [comment]
Hi @shenRicky,

Sorry for the late reply. GATNE is mainly proposed for the multiplex link prediction task and I'm not sure whether it will get high performance on the node classification task. And edge features are not considered in our paper. Maybe you can propose your own model that captures edge features based on GATNE models.
