### ISSUE TITLE
The data pre-processing problem.

### ISSUE THREAD

**Issue by hwZhang98** [THUDM/GATNE#59]
Hi!

This is a wonderful article! I'm very interested in this direction. But I'm having some difficulties and I need your help.

When I scanned the Github file library, I found there is no data pre-processing files. I'm new to graph embedding. The data pre-processing files I've seen before are all for homogenous graphs. So, could you upload your data processing file to Github or send it  to me by email.My email is   'zhanghaowen@hdu.edu.cn'.

I hope to hear from you soon.Thank you very much.

**Comment by cenyk1230** [comment]
Hi @hwZhang98,

Thank you for your attention. The pre-processing procedure is very straight-forward and similar to that for homogeneous graphs. The processed data is formatted as edge list files (with true/false labels for validation/testing data). I think you can try to pre-process your own graphs.
