### ISSUE TITLE
edge embedding 

### ISSUE THREAD

**Issue by Yuminzhou** [THUDM/GATNE#6]
您好
我可以从代码里的final_model拿到node embedding
请问有什么办法可以拿到edge embedding吗
感谢

**Comment by cenyk1230** [comment]
emmm 可能paper中edge embedding这个词用得不太好。其实这里的edge embedding并不是指边的表征，指的的edge-specific node embedding，是总体的node embedding的一部分。

**Comment by Yuminzhou** [comment]
thanks!
