### ISSUE TITLE
feature.txt

### ISSUE THREAD

**Issue by yiji-gr** [THUDM/GATNE#60]
您好，假如我现在一个用户节点有两个属性，年龄和性别，均是one-hot，请问在feature.txt中是怎么写的，是直接两个one-hot concat写在一行吗？
谢谢！

**Comment by cenyk1230** [comment]
Hi @yiji-gr,

Thank you for your attention to our code. The answer is yes. You should concatenate all the features of each node into one line of `feature.txt`.
