### ISSUE TITLE
基于tensorflow2的GATNE

### ISSUE THREAD

**Issue by jiajiewang0326** [THUDM/GATNE#61]
您好！
      看了你的论文和代码后我产生了很大的兴趣，它们都是开创性的工作。然后我正在用tensorflow==2.1.0实现GATNE，因为据我所知目前开源社区中并没有相关分享。不知道你是否有时间，我们可以合作一起开发tf2.1的GATNE，一起扩大GATNE的影响力。

**Comment by cenyk1230** [comment]
Hi @jiajiewang0326,

Thank you for your attention to GATNE. It's my pleasure that you are trying to use tf-2 to re-implement GATNE. I'm sorry that I don't have enough time to develop it with you. But I will help you if you meet some trouble in the implementation. If you finally implement it and reproduce the results, I can add your github link in the README.
