### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by amir1065** [THUDM/GATNE#62]
Hi, thank you for your novel idea. I have two questions. I would appreciate your quick response.

1. How to get the embeddings of nodes and edges w.r.t. each edge type? Does the 'final_model' dictionary contain the embeddings of all the nodes?
2. Assume that I have a graph with different edge types (only one type of node). Two nodes are connected with multiple types of edges with specific weights on each. Do you have any idea how to utilize your code to get the embeddings of the graph w.r.t. each edge type?    

Thank you in advance.

**Comment by cenyk1230** [comment]
Hi @amir1065,

Thank you for your interest. 
1) Yes, you can save the `final_model` to get the embeddings of nodes for different edge types.
2) The current version of our code can't handle edge weights, maybe you can ignore the weights and transform your data to our format and run our model.

**Comment by amir1065** [comment]
Thank you @cenyk1230 for the quick response.

Regarding the second question, what is your opinion if I modify the random walk code to the weighted one? Does that make sense to you?

Sorry for disturbing and thank you.

**Comment by cenyk1230** [comment]
Hi @amir1065,

Yes, it does make sense that using the weighted random walk to deal with weighted graphs.

**Comment by naman-ali** [comment]
Hi @amir1065,

Were you able to integrate GATNE for weighted graphs? Can you share the codes or explain how you've done that?

Thank you.
