### ISSUE TITLE
In GATNE-I ， how can we make the neighbor of the unoberved data?

### ISSUE THREAD

**Issue by 1145520074** [THUDM/GATNE#65]
Thanks for your work ,  I have one question , in GATNE-I , how do we make the neighborhoods of the unoberved data? Thank you very much.

**Comment by cenyk1230** [comment]
Hi @1145520074,

Thank you very much for your attention to GATNE. For the unobserved node with few neighbors, we can set itself as its neighbors for padding. The node feature of unobserved data will be mainly used for computing the node embedding.
