### ISSUE TITLE
How to genereate feature.txt

### ISSUE THREAD

**Issue by Reid00** [THUDM/GATNE#66]
![image](https://user-images.githubusercontent.com/38450639/95736821-520d0480-0cb9-11eb-98b0-6b7ea8a237f5.png)

您好，请问这个feature.txt 是怎么生成的？
我开始的理解是User Item 两种实体的feature one-hot concat, 但是看到数据集之后，发现很多第一列都是非1、0 的小数，不太理解这个部分是怎么生成的。

**Comment by cenyk1230** [comment]
Hi @Reid00,

Thank you for your attention to our work. For the categorical attribute, we use one-hot encoding to transform them. The non-zero/one numbers are continuous node attributes, e.g., prices for Amazon items.

**Comment by Reid00** [comment]
thank you very much. 
BTW, i note the pytorch version still not exist code how to use feature text, do you will update that?

**Comment by cenyk1230** [comment]
@Reid00,

I'm sorry that the code of the PyTorch version still can't use node features. I will update the code in the next several weeks. If you are in a hurry, you can use the TensorFlow code for your experiments.

**Comment by cenyk1230** [comment]
Hi @Reid00,

I have updated the PyTorch version of our GATNE for node features.

**Comment by Reid00** [comment]
Got it, thank you very much for your wonderful work.
