### ISSUE TITLE
node embedding

### ISSUE THREAD

**Issue by kanhuimin** [THUDM/GATNE#68]
Hello, your work is very good. I would like to ask if your work is applicable to the situation that there is only one type of node, and there may be multiple relationships between nodes, but only one kind of relationship association is selected between node pairs? What's more, in your work, you get the embedding of each node for each relationship. Do you support the node embedding of the target node in multiple relationships? We are looking forward to your reply

**Comment by cenyk1230** [comment]
Hi @kanhuimin,

Thank you for your interest in our work. 

The situation that you say is a little different from our setting. I just come up with a solution to your situation. You can add a base relationship in your graph (two nodes have a base relationship if and only if there is another relationship between them). Then you can use GATNE to generate node embeddings on this extended graph. The node embedding under the base relationship can be used for the downstream node classification task. I think you can have a try if you want to use GATNE models.
