### ISSUE TITLE
About the Alibaba-S dataset

### ISSUE THREAD

**Issue by guo-vii** [THUDM/GATNE#69]
Thanks for your work. As you say in appendix A.1 in the paper, "our partition of the three public datasets and the Alibaba-S dataset are available". So could you share the Alibaba-S dataset? I'm looking forward to your reply. Thanks a lot.

**Comment by cenyk1230** [comment]
Hi @guo-vii,

Sorry, Alibaba datasets used by our paper are unavailable. If you are very interested in the Alibaba dataset, you can find similar datasets in the Tianchi Platform such as https://tianchi.aliyun.com/dataset/dataDetail?dataId=649.
