### ISSUE TITLE
edge prediction 

### ISSUE THREAD

**Issue by Yuminzhou** [THUDM/GATNE#7]
您好 不好意思 我有几个小问题
1. 请问如果我想预测node1和node2之间哪个edges type的probability最高, 以致于可以预测edge type. 请问您有什么建议吗?
2. 请问paper中的context embedding是怎么算出来的, 不好意思这块不是很明白, 谢谢

![image](https://user-images.githubusercontent.com/22050071/61019305-43f07a00-a3cc-11e9-95a3-75e4f0eec482.png)

**Comment by cenyk1230** [comment]
1. 一种可能的方式是根据node1 node2在每种edge type下的emb计算出每种edge type下的similarity，然后进行比较（不一定make sense）。这里的similarity可以通过直接进行点积得到或者额外训练一个classifier来预测。
2. context embedding也是模型的参数，跟其他参数一起被优化的。

**Comment by Yuminzhou** [comment]
similarity是"node1 embedding" * "node2 embedding", 还是"node1 embedding" * "node2 context embedding"? 
因为上面的P(vj|vi)是"node1 embedding" * "node2 context embedding" 对吗?
感谢

**Comment by cenyk1230** [comment]
可以都试一下。不过确实"node1 embedding" * "node2 context embedding"更加make sense。
