### ISSUE TITLE
关于loss

### ISSUE THREAD

**Issue by foolishhmy** [THUDM/GATNE#70]
请问为什么计算loss的时候pair的两个点一个embedding来自于模型，另外一个embedding是context embedding(实现在loss中)，期待您的回复！

**Comment by cenyk1230** [comment]
Hi @foolishhmy,

Thank you for your attention to our work. From our modeling of `P_\theta(v_j|v_i)`, we use the embedding of `v_i` when it is treated as a vertex to predict the embedding of `v_j` when it is treated as a specific context. We follow this definition from a previous paper, _LINE: Large-scale Information Network Embedding_. You can see Section 4.1.2 of this paper for more details.

**Comment by yuanninesuns** [comment]
In the python 3 environment, I don't think this line of code can make the `walk` function get the global variable G
`all_walks = list(pool.imap(walk, ((walk_length, node, '') for node in tqdm(self.node_list(nodes, num_walks))), chunksize=256))`
