### ISSUE TITLE
环境版本

### ISSUE THREAD

**Issue by Shodowelf** [THUDM/GATNE#71]
您好，首先非常感谢您开源您的工作。我在安装pip install -r requirements.txt，没法安装，所以我把需要的库单个安装上了，在运行时碰到了版本错误的问题，File "E:\1219\anaconda\envs\gatne\lib\site-packages\gensim\models\ldamodel.py", line 54, in <module> from scipy.misc import logsumexp ImportError: cannot import name 'logsumexp'
所以，我想咨询一下您requirements中的包的版本。

**Comment by cenyk1230** [comment]
Hi @Shodowelf,

Thank you for your interest in our work. It seems that the new version of `scipy` moved `scipy.misc` to `scipy.special`. The version `scipy==1.2.1` is fine for our code and maybe you can degrade `scipy` to 1.2.1. I will add this version number of `scipy` to requirements soon.

**Comment by Shodowelf** [comment]
Thank you very much.
