### ISSUE TITLE
多线程操作global变量很危险

### ISSUE THREAD

**Issue by yuanninesuns** [THUDM/GATNE#75]
walk.py中的多线程对gobal变量G进行操作，存在一定的问题，不知道你们改动代码之后是否能跑通？我这边显示报错name 'G' is not defined

**Comment by cenyk1230** [comment]
Hi @yuanninesuns,

Thank you for your attention to our work and for pointing it out. What's your environment for running the code? Maybe I should use an initializer function of `multiprocessing.Pool` for passing the graph G to the subprocesses?

**Comment by yuanninesuns** [comment]
In the python 3 environment, I don't think this line of code can make the `walk` function get the global variable G
`all_walks = list(pool.imap(walk, ((walk_length, node, '') for node in tqdm(self.node_list(nodes, num_walks))), chunksize=256))`

**Comment by cenyk1230** [comment]
I did run the latest code in my environment (Ubuntu 18.04.2 LTS, Python 3.6). 
Please give more details of your running environment. For example,
- Operating System (Linux/Mac OS/Windows): 
- Python Version (3.x):

**Comment by yuanninesuns** [comment]
Windows
Python 3.6

**Comment by yuanninesuns** [comment]
I tried to run this code on Linux and found that it worked

**Comment by cenyk1230** [comment]
Hi @yuanninesuns,

I have pushed a new commit to the `dev` branch. Could you please help me find out whether that version works in Windows?

**Comment by yuanninesuns** [comment]
Great. It works on windows.Thank you very much.

**Comment by cenyk1230** [comment]
Thanks! I will close the issue. You can submit a new issue if you find other problems.
