### ISSUE TITLE
the problem of global

### ISSUE THREAD

**Issue by yuanninesuns** [THUDM/GATNE#77]
The following cannot find `node_type` on Windows, even after you modify it. It may also be the problem of `global`
`walks = list(pool.imap(walk, ((walk_length, node, schema_iter) for node in tqdm(self.node_list(nodes, num_walks)) if schema_iter.split('-')[0] == node_type[node]), chunksize=512))`

**Comment by cenyk1230** [comment]
Hi @yuanninesuns,

It seems that I forget to modify the `node_type` in the `simulate_walks` to `self.node_type`. You can have a try using the new `dev` branch.
