### ISSUE TITLE
About the "node_type.txt"

### ISSUE THREAD

**Issue by Carmen-Y-Wang** [THUDM/GATNE#78]
Hi there, nice to read your great work! 

I am new to metapath. Could you please prove a specific example for "node_type.txt"? Or just the "head" should also be fine.

With many thanks!

**Comment by cenyk1230** [comment]
Hi @Carmen-Y-Wang,

Thank you for your attention to our work. For example, if the schema is `U-I-U`, then the "node_type.txt" file should be like
1 U
2 U
3 I
4 I
...
(nodes 1, 2 belong to U, and nodes 3, 4 belong to I)

**Comment by Carmen-Y-Wang** [comment]
Thanks for your reply! 
So what if we have multiple kinds of schemas? Shall we build multiple files? 

Best,

**Comment by cenyk1230** [comment]
@Carmen-Y-Wang Sorry for the late reply. One node type file is enough. And you can pass multiple schemas to our model (e.g., --schema U-I-U,I-U-I).

**Comment by Carmen-Y-Wang** [comment]
Thanks for your great help!!
