### ISSUE TITLE
questions  for  training  with GPU

### ISSUE THREAD

**Issue by sudongxiang** [THUDM/GATNE#82]
Firstly, I have to say, nice work of you, for GATNE is a beautiful model.
However, when I start training my own job, training cost too much time. I am wondering, how to solve the problem of low speed in your production environment.
Is using GPU the key to solving this problem？

**Comment by cenyk1230** [comment]
Hi @sudongxiang,

Thank you for your interest in our work. It really needs GPU for speed-up model training.
