### ISSUE TITLE
Hyper-parameters for Twitter dataset?

### ISSUE THREAD

**Issue by Veronicium** [THUDM/GATNE#88]
Hi, I'm trying to reproduce the results in your paper. I use the same hyper-parameters as in utils.py and the performance on Amazon/Youtube is as good as reported , but the ROC-AUC, PR-AUC, F1 on Twitter dataset is only around 0.76, 0.77, 0.71.

Could you share the hyper-parameters you use for the Twitter dataset? Thank you.

**Comment by cenyk1230** [comment]
@Veronicium Do you run the `main.py` and set the `--eval-type 1`?

**Comment by Veronicium** [comment]
> @Veronicium Do you run the `main.py` and set the `--eval-type 1`?

I see. I was running main-Pytorch.py with --eval-type 'all'.
Thanks.

**Comment by Veronicium** [comment]
> @Veronicium Do you run the `main.py` and set the `--eval-type 1`?

Yes. Running 'main.py' with '--eval-type 1' does give the desired performance. Could you think of a possible reason? The hyper-parameters in both version is the same and I can't see there's anything different in model structure.

**Comment by cenyk1230** [comment]
@Veronicium As the PyTorch doesn't provide nce_loss, I implement a naive version of negative sampling (see [NSLoss](https://github.com/THUDM/GATNE/blob/master/src/main_pytorch.py#L106)). It seems that the implemented NSLoss doesn't well work.
