### ISSUE TITLE
Can GATNE be applied to weighted graph?

### ISSUE THREAD

**Issue by Crystalsudo** [THUDM/GATNE#9]
Hi！
Although I have already read through your paper, I just want to check with you whether this approach can be applied to weighted graph?

**Comment by cenyk1230** [comment]
Sorry, this version of GATNE code doesn't support weighted graphs. But our approach can be applied to weighted graphs if we use the weighted random walk method. We will support weighted graphs soon. Maybe you can ignore the edge weights and try GATNE now.

**Comment by Crystalsudo** [comment]
Got it! Thank you!
