### ISSUE TITLE
The meaning of each edge type in youtube dataset?

### ISSUE THREAD

**Issue by Veronicium** [THUDM/GATNE#91]
Hi, I read your paper and it says the five edge types in Youtube datasets are "contact, shared friends, shared subscription, shared subscriber and shared favorite videos". How do that correspond to the edge types "1,2,3,4,5" in your dataset? 
I tried to follow the link provided in your paper but the website is down.

Thank you.

**Comment by cenyk1230** [comment]
@Veronicium I think the edge types "1, 2, 3, 4, 5" correspond to "contact, shared friends, shared subscription, shared subscriber and shared favorite videos", respectively.
